# Generated by Django 4.0.5 on 2022-06-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_categoria_idcategoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='rut de persona')),
                ('nombre', models.CharField(max_length=40, verbose_name='nombre persona')),
                ('fechaNac', models.CharField(max_length=8, verbose_name='fecha de nacimiento')),
                ('telefono', models.CharField(max_length=9, verbose_name='telefono emergencia')),
            ],
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
