# Generated by Django 4.0.5 on 2022-06-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_persona_remove_vehiculo_categoria_delete_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fechaNac',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='persona',
            name='rut',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(max_length=9),
        ),
    ]
