# Generated by Django 4.0.5 on 2022-06-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_persona_fechanac_alter_persona_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='antecedentes',
            field=models.TextField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
