# Generated by Django 4.0.5 on 2022-06-08 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sexo_persona_antecedentes_persona_fechaing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='antecedentes',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fechaIng',
            field=models.CharField(max_length=8, null=True, verbose_name='fecha Ingreso'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fechaNac',
            field=models.CharField(max_length=8, verbose_name='fecha nacimiento'),
        ),
        migrations.CreateModel(
            name='Evoluciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('evolucion', models.TextField(max_length=200)),
                ('rutPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.persona')),
            ],
        ),
    ]
