# Generated by Django 4.0.5 on 2022-06-08 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_persona_antecedentes_alter_persona_fechaing_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Evoluciones',
            new_name='Evolucion',
        ),
    ]
