# Generated by Django 4.0.5 on 2022-06-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_evoluciones_evolucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aportadores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=40)),
                ('correo', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=10)),
            ],
        ),
    ]
