# Generated by Django 4.0.5 on 2022-06-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_aportadores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolucion',
            name='fecha_creacion',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='evolucion',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
