# Generated by Django 4.0.5 on 2022-06-17 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_evolucion_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='mandatoAportador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField(max_length=30)),
                ('nro_tarjeta', models.CharField(max_length=30)),
                ('dia_pago', models.CharField(max_length=2)),
                ('fecha_transaccion', models.CharField(max_length=10)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
    ]
