# Generated by Django 4.0.5 on 2022-06-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_mandatoaportador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandatoaportador',
            name='monto',
            field=models.IntegerField(),
        ),
    ]
