# Generated by Django 4.0.5 on 2022-06-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_pagosaportador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id_gasto', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_gasto', models.DateTimeField(auto_now_add=True)),
                ('monto', models.IntegerField()),
                ('detalle', models.CharField(max_length=300)),
            ],
        ),
    ]
