# Generated by Django 4.0.5 on 2022-06-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_gastos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id_bodega', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=40)),
                ('valor', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=40)),
                ('formato', models.CharField(max_length=30)),
                ('codigo', models.CharField(max_length=40)),
                ('valor', models.IntegerField()),
            ],
        ),
    ]
