# Generated by Django 4.0.5 on 2022-06-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_bodega_medicamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamentos',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='medicamentos',
            name='precio_Total',
            field=models.IntegerField(null=True),
        ),
    ]
